import type { NextPage } from 'next'
import { NextSeo as SEO } from 'next-seo'
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { Button, Container, Footer, H1, Navigation } from '@/components'
import config from '@/modules/config'
import { useRouter } from 'next/router'

const desktopLinks = [
  { name: 'Terms & conditions', href: '/terms' }, 
]

const TermsPage: NextPage = () => {
  const router = useRouter()

  const { otherPageLinks } = config

  return (
    <div className="h-screen bg-center bg-repeat-x bg-cover bg-bubble">
      <SEO
        title="Opening soon"
        description="Yubba World is a collection of randomly generated digital collectibles of various rarity living on the Ethereum blockchain as ERC-721.10,000 unique characters of staggering variety"
      />

      <Navigation
        desktopLinks={desktopLinks}
        mobileLinks={otherPageLinks}
        action={
          <></>
          // <Link href="/minting" passHref>
          //   <Button variant="primary">
          //     Get minting
          //   </Button>
          // </Link>
        }
      />

      <section className="py-8 pt-20">
        <Container>
          <div className="relative h-24 mx-auto mb-8">
            <Image src="/yubba-world-1line.png" layout="fill" objectFit="contain" alt="Yubba World" />
          </div>

          {/* <div className="absolute items-center hidden align-middle top-60 left-40 md:block ">
            <Button variant="white" size="large" style={{ justifyContent: "center" }} block onClick={() => router.back()}>
              <div className="w-[80px] font-normal grid grid-cols-2">
                <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 " fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                Back
              </div>
            </Button>
          </div> */}

          <div className="flex flex-row items-center w-full">
            <div className="">
              <Button variant="white" style={{ justifyContent: "center" }} block onClick={() => router.back()}>
                <div className="w-[80px] font-normal grid grid-cols-2">
                  <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 " fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                  Back
                </div>
              </Button>
            </div>

            <div className="flex flex-1">
              <H1 className="text-center" style={{ marginTop: '40px', marginBottom: '48px' }}>
                Terms & Conditions
              </H1>
            </div>
          </div>

          <p className="font-bold text-secondary">
            Last updated on 10th Oct, 2021
          </p>

          <br />

          <p className="text-secondary">
            This website is operated by Yubba World. Throughout the site, the term « Yubba World », « we », « us » or « our » as the context may require, refer to Yubba World. « Yubba(s) », « Yubba NFT », refer to individual pieces of NFT artwork, refer by visiting our site and/or purchasing something from us, you engage in our Service and agree to be bound by the following terms and conditions.
            <br /><br />
            We reserve the right to update, change or replace any part of these Terms of services without prior written notice at any time, and it is your responsibility to periodically review these Terms of Uses to stay informed of updates. Any changes to the Terms will be in effect as of the « last updated » referenced on the site.
            <br /><br />
            Your continued use of this site after the last updated dates will constitute your acceptance of agreement.
            <br /><br />
            By visiting the website of our products merchants, in particular www.opensea.io, you also engage and agree to be bound by their terms and conditions.
            <br /><br />
            This website is for informational purposes and serves as a binding contract for purchasers of Yubba NFTs.
            <br /><br />
            Yubba World is a generative collection of digital artwork (NFTs) housed and run on the Ethereum Network. Users and Collector of these NFTs are solely responsible for the safety and the management of their own private assets, which include but are not limited to Ethereum Wallets, validating all transactions and contracts generated by this website prior to and after purchases.
            <br /><br />
            Users certify through purchase that they understand that, as the Yubba World smart contract runs on the Ethereum network and is bound by their system and terms, there is no ability to undo, reverse, or restore any transactions.
            <br /><br />
            Any connected services included this website are provided “as is” and “as available” without any warranty of any kind. Use of this website constitutes your agreement that you are accepting sole responsibility for any and all transactions involving Yubba World digital collectibles.
            <br /><br />
            By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence.
            <br /><br />
            You may not use our products and/or services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).
          </p>
          <p className="mt-10 text-secondary  font-bold text-2xl uppercase tracking-[12px]">
            Ownership
          </p>

          <br />

          <p className="text-secondary">
            When you purchase your Yubba NFT, You Own the NFT : the ownership is transferred to you on the Ethereum blockchain for that individual piece of Art combination of traits and number. Ownership of the NFT is ruled by the smart contract and the Ethereum Network terms. We, Yubba World, have no ability to alter, freeze, seize or modify the ownership of any Yubba NFT.
          </p>
          <p className="mt-10 text-secondary  font-bold text-2xl uppercase tracking-[12px]">
            Personal usage
          </p>

          <br />

          <p className="text-secondary">
            Subject to your continued acceptance with these terms, Yubba World allows you a worldwide, royalty-free licence to use, copy and display the purchased Art, along with any derivative artwork or extensions that you could create or use, limited by the following purposes : (i) for your own personal, non commercial use; (ii) as part of a marketplace that allows the purchase and sales of your Yubba / NFT, as long as the marketplace cryptographically verifies that you are the owner, to ensure that only the actual owner has the right to display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement or participation of your Yubba(s), provided that the website or the application cryptographically verifies each Yubba owner’s right to display the Art for their Yubba(s), to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the actual owner of the Yubba(s) leaves the website or application.
          </p>

          <p className="mt-10 text-secondary  font-bold text-2xl uppercase tracking-[12px]">
            Commercial usage
          </p>

          <br />

          <p className="text-secondary">
            Subject to actual owner of Yubba NFTs continued compliance with these Terms, Yubba World grant you an unlimited, worldwide licence to use, copy and display the purchased Art for the purpose of creating derivative works based upon the Art (« COMMERCIAL USAGE »). The only exception being not to carry out 3D modeling (sale of figurines) because we reserve it for the physical part of our drop. Examples of specified Commercial Use would be the use of the Art to produce and sell physical merchandise products (T-Shirt, Posters, etc.) displaying copies of the purchased Art. Please be aware that nothing in this section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of Yubba World generally, provided that the marketplace cryptographically verifies each Yubba owner’s right to display the Art of their Yubba to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Yubba World generally, provided that the third party website or application cryptographically verifies each Yubba owner’s rights to display the Art for their Yubba to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased Yubba(s) leaves the website/application; or (iii) earning revenue from any of the foregoing.
            <br /><br />

            Further, Yubba World reserves the right to use ANY character, including : print or digital advertising, or any purely creative media (including short film, anime, etc.) in support of the Yubba World community and message.
            <br /><br />
            However, you cannot use the artwork in connection with images of hatred, violence or any other inappropriate behavior. The License granted in above only applies to the extent that you continue to own the relevant NFT. If at any time you trade, donate, giveaway, transfer or otherwise dispose of your NFT for any reason, the license granted above will immediately expire, without notice, and you will have no further right in or to the artwork of this NFT.


          </p>

          <p className="mt-10 text-secondary  font-bold text-2xl uppercase tracking-[12px]">
            Intellectual property
          </p>

          <br />

          <p className="text-secondary">
            Other than the rights to the Art, nothing gives you any rights to any other trademarks or other intellectual property rights belonging to Yubba World including, without limitation Yubba World, Yubba World and the associated logos. All of these rights are expressly reserved in the name of Yubba World.
          </p>
          <Footer />
        </Container>
      </section>
    </div>
  )
}

export default TermsPage
